/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucenfotec.soft2.ui;

import cr.ac.ucenfotec.soft2.usuarios.GestorUsuarios;
import cr.ac.ucenfotec.soft2.usuarios.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Carballo Villalobos, Kenner Gamboa Suarez, Victor Calvo
 * Saldana
 */
public class AdministrarUsuariosFrame extends javax.swing.JFrame {

    public GestorUsuarios gestor = new GestorUsuarios();

    public void cargarUsuariosEnTabla(GestorUsuarios gestor) {
        DefaultTableModel modelo = (DefaultTableModel) jTableUsuarios.getModel();
        modelo.setRowCount(0); //LIMPIAR TABLA

        for (Usuario u : gestor.getUsuarios()) {
            Object[] fila = {
                u.getNombre(),
                u.getApellido(),
                u.getCedula(),
                u.getRol()
            };
            modelo.addRow(fila);
        }
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdministrarUsuariosFrame.class.getName());

    /**
     * Creates new form AdministrarUsuariosFrame
     */
    public AdministrarUsuariosFrame() {
        initComponents();
        cargarUsuariosEnTabla(gestor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonMenuAdmin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonAgregarUsuario = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        botonModificarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrador de usuarios"));

        botonMenuAdmin.setText("Menu Principal");
        botonMenuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuAdminActionPerformed(evt);
            }
        });

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Cédula", "Rol"
            }
        ));
        jScrollPane2.setViewportView(jTableUsuarios);

        jLabel1.setText("Lista de Usuarios");

        botonAgregarUsuario.setText("Agregar Usuario");
        botonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarUsuarioActionPerformed(evt);
            }
        });

        botonEliminarUsuario.setText("Eliminar Usuario");
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });

        botonModificarUsuario.setText("Editar Usuario");
        botonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonMenuAdmin)
                                .addGap(18, 18, 18)
                                .addComponent(botonAgregarUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminarUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(botonModificarUsuario)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenuAdmin)
                    .addComponent(botonAgregarUsuario)
                    .addComponent(botonEliminarUsuario)
                    .addComponent(botonModificarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuAdminActionPerformed

        this.setVisible(false);
        new MenuGerenteFrame().setVisible(true);
    }//GEN-LAST:event_botonMenuAdminActionPerformed

    private void botonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarUsuarioActionPerformed
        this.setEnabled(false);

        AgregarNuevoUsuarioFrame nuevoFrame = new AgregarNuevoUsuarioFrame(gestor, this);

        nuevoFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                AdministrarUsuariosFrame.this.setEnabled(true);
                AdministrarUsuariosFrame.this.toFront();
                AdministrarUsuariosFrame.this.requestFocus();
            }
        });
        
        nuevoFrame.setVisible(true);
    }//GEN-LAST:event_botonAgregarUsuarioActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        int filaSeleccionada = jTableUsuarios.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para eliminar.");
            return;
        }

        // Obtener la cédula del usuario seleccionado
        String cedulaUsuario = jTableUsuarios.getValueAt(filaSeleccionada, 2).toString();
        String nombreUsuario = jTableUsuarios.getValueAt(filaSeleccionada, 0).toString();

        // Confirmar eliminación
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar al usuario " + nombreUsuario + "?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Buscar y eliminar el usuario de la lista
            gestor.getUsuarios().removeIf(usuario -> usuario.getCedula().equals(cedulaUsuario));

            // Actualizar la tabla
            cargarUsuariosEnTabla(gestor);

            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
        }
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    private void botonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarUsuarioActionPerformed
        int filaSeleccionada = jTableUsuarios.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para modificar.");
            return;
        }
        
        String cedula = jTableUsuarios.getValueAt(filaSeleccionada, 2).toString();
        Usuario usuario = null;
        
        // Buscar el usuario por cédula
        for (Usuario u : gestor.getUsuarios()) {
            if (u.getCedula().equals(cedula)) {
                usuario = u;
                break;
            }
        }
        
        if (usuario != null) {
            this.setEnabled(false);
            
            AgregarNuevoUsuarioFrame frame = new AgregarNuevoUsuarioFrame(gestor, this, usuario);
            
            frame.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    AdministrarUsuariosFrame.this.setEnabled(true);
                    AdministrarUsuariosFrame.this.toFront();
                    AdministrarUsuariosFrame.this.requestFocus();
                }
            });
            
            frame.setVisible(true);
        }
    }//GEN-LAST:event_botonModificarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdministrarUsuariosFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarUsuario;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JButton botonMenuAdmin;
    private javax.swing.JButton botonModificarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUsuarios;
    // End of variables declaration//GEN-END:variables
}
