/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucenfotec.soft2.ui;

import cr.ac.ucenfotec.soft2.usuarios.GestorUsuarios;
import cr.ac.ucenfotec.soft2.usuarios.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Carballo Villalobos, Kenner Gamboa Suarez, Victor Calvo
 * Saldana
 */
public class AgregarNuevoUsuarioFrame extends javax.swing.JFrame {

    public GestorUsuarios gestor;
    private AdministrarUsuariosFrame framePadre;
    private Usuario usuarioAEditar; // null si es nuevo, con datos si es edición
    private boolean modoEdicion;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgregarNuevoUsuarioFrame.class.getName());

    /**
     * Constructor para agregar nuevo usuario
     */
    public AgregarNuevoUsuarioFrame(GestorUsuarios gestor, AdministrarUsuariosFrame framePadre) {
        this.gestor = gestor;
        this.framePadre = framePadre;
        this.usuarioAEditar = null;
        this.modoEdicion = false;
        initComponents();
    }
    
    /**
     * Constructor para modificar usuario existente
     */
    public AgregarNuevoUsuarioFrame(GestorUsuarios gestor, AdministrarUsuariosFrame framePadre, Usuario usuario) {
        this.gestor = gestor;
        this.framePadre = framePadre;
        this.usuarioAEditar = usuario;
        this.modoEdicion = true;
        initComponents();
        cargarDatosUsuario();
        configurarModoEdicion();
    }
    
    private void cargarDatosUsuario() {
        if (usuarioAEditar != null) {
            textNuevoUsuarioNombre.setText(usuarioAEditar.getNombre());
            textNuevoUsuarioApellido.setText(usuarioAEditar.getApellido());
            textNuevoUsuarioCedula.setText(usuarioAEditar.getCedula());
            dropdownNuevoUsuarioRol.setSelectedItem(usuarioAEditar.getRol());
        }
    }
    
    private void configurarModoEdicion() {
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificar Usuario"));
        textNuevoUsuarioCedula.setEnabled(false); // No permitir cambiar la cédula
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNuevoUsuarioNombre = new javax.swing.JTextField();
        textNuevoUsuarioApellido = new javax.swing.JTextField();
        textNuevoUsuarioCedula = new javax.swing.JTextField();
        dropdownNuevoUsuarioRol = new javax.swing.JComboBox<>();
        botonAceptarNuevoUsuario = new javax.swing.JButton();
        botonCancelarNuevoUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Usuario"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Cédula:");

        jLabel4.setText("Rol:");

        dropdownNuevoUsuarioRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Barista" }));

        botonAceptarNuevoUsuario.setText("Aceptar");
        botonAceptarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarNuevoUsuarioActionPerformed(evt);
            }
        });

        botonCancelarNuevoUsuario.setText("Cancelar");
        botonCancelarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarNuevoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNuevoUsuarioNombre)
                    .addComponent(textNuevoUsuarioApellido)
                    .addComponent(textNuevoUsuarioCedula)
                    .addComponent(dropdownNuevoUsuarioRol, 0, 291, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(botonAceptarNuevoUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelarNuevoUsuario)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNuevoUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNuevoUsuarioApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNuevoUsuarioCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dropdownNuevoUsuarioRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptarNuevoUsuario)
                    .addComponent(botonCancelarNuevoUsuario))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarNuevoUsuarioActionPerformed
        String nombre = textNuevoUsuarioNombre.getText().trim();
        String apellido = textNuevoUsuarioApellido.getText().trim();
        String cedula = textNuevoUsuarioCedula.getText().trim();
        String rol = dropdownNuevoUsuarioRol.getSelectedItem().toString();

        if (nombre.isEmpty() || apellido.isEmpty() || cedula.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Todos los campos deben estar llenos.");
            return;
        }

        if (modoEdicion) {
            // Modo edición: actualizar usuario existente
            usuarioAEditar.setNombre(nombre);
            usuarioAEditar.setApellido(apellido);
            usuarioAEditar.setRol(rol);
            JOptionPane.showMessageDialog(rootPane, "Usuario modificado correctamente.");
        } else {
            // Modo agregar: verificar cédula duplicada y agregar nuevo
            boolean cedulaDuplicada = false;
            for (Usuario u : gestor.getUsuarios()) {
                if (u.getCedula().equals(cedula)) {
                    cedulaDuplicada = true;
                    break;
                }
            }

            if (cedulaDuplicada) {
                JOptionPane.showMessageDialog(rootPane, "Ya existe un usuario con esta cédula.");
                return;
            }
            
            gestor.agregarUsuario(nombre, apellido, cedula, rol);
            JOptionPane.showMessageDialog(rootPane, "Usuario agregado correctamente.");
        }
        
        if (framePadre != null) {
            framePadre.cargarUsuariosEnTabla(gestor);
        }
        
        this.dispose();
    }//GEN-LAST:event_botonAceptarNuevoUsuarioActionPerformed

    private void botonCancelarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarNuevoUsuarioActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarNuevoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarNuevoUsuario;
    private javax.swing.JButton botonCancelarNuevoUsuario;
    private javax.swing.JComboBox<String> dropdownNuevoUsuarioRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textNuevoUsuarioApellido;
    private javax.swing.JTextField textNuevoUsuarioCedula;
    private javax.swing.JTextField textNuevoUsuarioNombre;
    // End of variables declaration//GEN-END:variables
}
