/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucenfotec.soft2.ui;

import cr.ac.ucenfotect.soft2.inventario.Inventario;
import cr.ac.ucenfotect.soft2.inventario.Producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class InventarioFrame extends javax.swing.JFrame {
    
    private Inventario inventario = new Inventario();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventarioFrame.class.getName());

    /**
     * Creates new form InventarioFrame
     */
    public InventarioFrame() {
        initComponents();
        cargarProductosEnTabla();
    }
    
    public void cargarProductosEnTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        
        for (Producto p : inventario.obtenerTodosLosProductos()) {
            Object[] fila = {
                p.getCodigoProducto(),
                p.getNombreProducto(),
                p.getCategoriaProducto(),
                p.getPrecioProducto(),
                p.getCantidadStock()
            };
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonMenuPrincipal = new javax.swing.JButton();
        botonVerProductos = new javax.swing.JButton();
        botonAgregarProductos = new javax.swing.JButton();
        botonModificarProductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventario"));

        botonMenuPrincipal.setText("Menú Principal");
        botonMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuPrincipalActionPerformed(evt);
            }
        });

        botonVerProductos.setText("Actualizar");
        botonVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerProductosActionPerformed(evt);
            }
        });

        botonAgregarProductos.setText("Agregar Producto");
        botonAgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProductosActionPerformed(evt);
            }
        });

        botonModificarProductos.setText("Modificar Producto");
        botonModificarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProductosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Categoría", "Precio", "Cantidad Stock"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Lista de Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonMenuPrincipal)
                                .addGap(18, 18, 18)
                                .addComponent(botonVerProductos)
                                .addGap(18, 18, 18)
                                .addComponent(botonAgregarProductos)
                                .addGap(18, 18, 18)
                                .addComponent(botonModificarProductos))
                            .addComponent(jLabel1))
                        .addGap(0, 304, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenuPrincipal)
                    .addComponent(botonVerProductos)
                    .addComponent(botonAgregarProductos)
                    .addComponent(botonModificarProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuPrincipalActionPerformed
        this.setVisible(false);
        new MenuGerenteFrame().setVisible(true);
    }//GEN-LAST:event_botonMenuPrincipalActionPerformed

    private void botonVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerProductosActionPerformed
        // Actualizar la tabla
        cargarProductosEnTabla();
    }//GEN-LAST:event_botonVerProductosActionPerformed

    private void botonAgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProductosActionPerformed
        String codigo = JOptionPane.showInputDialog("Código del producto:");
        String nombre = JOptionPane.showInputDialog("Nombre del producto:");
        String tipo = JOptionPane.showInputDialog("Tipo (Café, Bebida Fría, Pastelería):");
        double precio = Double.parseDouble(JOptionPane.showInputDialog("Precio:"));
        int cantidad = Integer.parseInt(JOptionPane.showInputDialog("Cantidad en stock:"));

        Producto nuevo = new Producto(codigo, nombre, tipo, precio, cantidad);
        inventario.agregarProducto(nuevo);
        JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");
    }//GEN-LAST:event_botonAgregarProductosActionPerformed

    private void botonModificarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProductosActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog("Código del producto a modificar:");
        Producto p = inventario.buscarProducto(codigo);
        if (p != null) {
            p.setNombreProducto(JOptionPane.showInputDialog("Nuevo nombre:", p.getNombreProducto()));
            p.setCategoriaProducto(JOptionPane.showInputDialog("Nuevo tipo:", p.getCategoriaProducto()));
            p.setPrecioProducto(Double.parseDouble(JOptionPane.showInputDialog("Nuevo precio:", p.getPrecioProducto())));
            p.setCantidadStock(Integer.parseInt(JOptionPane.showInputDialog("Nueva cantidad:", p.getCantidadStock())));
            JOptionPane.showMessageDialog(this, "Producto modificado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
        }
    }//GEN-LAST:event_botonModificarProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InventarioFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarProductos;
    private javax.swing.JButton botonMenuPrincipal;
    private javax.swing.JButton botonModificarProductos;
    private javax.swing.JButton botonVerProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
