/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucenfotec.soft2.ui;

import static cr.ac.ucenfotec.soft2.app.Utilities.preguntarSioNo;
import cr.ac.ucenfotec.soft2.usuarios.GestorUsuarios;

/**
 *
 * @author Carlos Carballo Villalobos, Kenner Gamboa Suarez, Victor Calvo
 * Saldana
 */
public class MenuGerenteFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuGerenteFrame.class.getName());

    /**
     * Creates new form MenuGerenteFrame
     */
    public MenuGerenteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAdminInventario = new javax.swing.JButton();
        botonAdminUsuarios = new javax.swing.JButton();
        botonAdminVentas = new javax.swing.JButton();
        botonAdminReportes = new javax.swing.JButton();
        botonAdminClientes = new javax.swing.JButton();
        botonAdminFacturacion = new javax.swing.JButton();
        botonAdminLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu Gerente"));

        botonAdminInventario.setText("Inventario");
        botonAdminInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminInventarioActionPerformed(evt);
            }
        });

        botonAdminUsuarios.setText("Administrar Usuarios");
        botonAdminUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminUsuariosActionPerformed(evt);
            }
        });

        botonAdminVentas.setText("Ventas");
        botonAdminVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminVentasActionPerformed(evt);
            }
        });

        botonAdminReportes.setText("Reportes");
        botonAdminReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminReportesActionPerformed(evt);
            }
        });

        botonAdminClientes.setText("Clientes");
        botonAdminClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminClientesActionPerformed(evt);
            }
        });

        botonAdminFacturacion.setText("Facturación");
        botonAdminFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminFacturacionActionPerformed(evt);
            }
        });

        botonAdminLogout.setText("Cerrar Sesión");
        botonAdminLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAdminLogout)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAdminReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAdminClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAdminFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAdminUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAdminInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAdminVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonAdminLogout)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAdminInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdminVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdminUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAdminClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdminFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdminReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAdminLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminLogoutActionPerformed
        boolean confirmarLogout;

        confirmarLogout = preguntarSioNo("Está seguro que desea cerrar la sesión?", "Confirmar Cerrar Sesión", this);

        if (confirmarLogout) {
            this.setVisible(false);
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_botonAdminLogoutActionPerformed

    private void botonAdminUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminUsuariosActionPerformed

        this.setVisible(false);

        GestorUsuarios gestor = new GestorUsuarios();
        AdministrarUsuariosFrame frame = new AdministrarUsuariosFrame();
        frame.cargarUsuariosEnTabla(gestor);
        frame.setVisible(true);
    }//GEN-LAST:event_botonAdminUsuariosActionPerformed

    private void botonAdminClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminClientesActionPerformed
        this.setVisible(false);
        new AdministrarClientesFrame("Gerente").setVisible(true);
    }//GEN-LAST:event_botonAdminClientesActionPerformed

    private void botonAdminInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminInventarioActionPerformed
        this.setVisible(false);
        new InventarioFrame().setVisible(true);
    }//GEN-LAST:event_botonAdminInventarioActionPerformed

    private void botonAdminVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAdminVentasActionPerformed

    private void botonAdminReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAdminReportesActionPerformed

    private void botonAdminFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminFacturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAdminFacturacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuGerenteFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdminClientes;
    private javax.swing.JButton botonAdminFacturacion;
    private javax.swing.JButton botonAdminInventario;
    private javax.swing.JButton botonAdminLogout;
    private javax.swing.JButton botonAdminReportes;
    private javax.swing.JButton botonAdminUsuarios;
    private javax.swing.JButton botonAdminVentas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
