/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ac.ucenfotec.soft2.ui;

import cr.ac.ucenfotec.soft2.clientes.GestorClientes;
import cr.ac.ucenfotec.soft2.facturacion.HistorialVentas;
import cr.ac.ucenfotec.soft2.inventario.Inventario;
import cr.ac.ucenfotec.soft2.inventario.Producto;
import cr.ac.ucenfotec.soft2.usuarios.Usuario;
import cr.ac.ucenfotec.soft2.ventas.Factura;
import cr.ac.ucenfotec.soft2.ventas.GestorVentas;
import cr.ac.ucenfotec.soft2.ventas.ItemCarrito;
import cr.ac.ucenfotec.soft2.ventas.Venta;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Carballo Villalobos
 */
public class VentasFrame extends javax.swing.JFrame {

    private javax.swing.JFrame menuPadre;
    private GestorClientes gestorClientes;
    private Inventario inventario;
    private GestorVentas gestorVentas;
    private String nombreUsuarioActual;
    private String rolUsuario;
    private ArrayList<ItemCarrito> carrito;
    private cr.ac.ucenfotec.soft2.clientes.Cliente clienteActual;
    private HistorialVentas historial;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentasFrame.class.getName());
    private Usuario usuario;

    /**
     * Creates new form VentasFrame
     */
    public VentasFrame(javax.swing.JFrame menuPadre, HistorialVentas historial, Inventario inventario, Usuario usuario) {
        this.menuPadre = menuPadre;
        this.historial = historial;
        this.inventario = inventario;
        this.usuario = usuario;
        this.rolUsuario = usuario.getRol();
        this.nombreUsuarioActual = usuario.getNombre();
        this.gestorClientes = new GestorClientes();
        this.gestorVentas = new GestorVentas();
        this.carrito = new ArrayList<>();
        this.clienteActual = null;

        initComponents();
        configurarComponentes();
        cargarProductosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCedulaCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        lblNombreCliente = new javax.swing.JLabel();
        btnRegistrarNuevoCliente = new javax.swing.JButton();
        btnMenuPrincipal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosDisponibles = new javax.swing.JTable();
        txtBuscarProductos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinnerCantidad = new javax.swing.JSpinner();
        btnAgregarAlCarrito = new javax.swing.JButton();
        btnLimpiarBusqueda = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        btnEliminarDelCarrito = new javax.swing.JButton();
        btnModificarCantidad = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCancelarVenta = new javax.swing.JButton();
        btnFinalizarVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo Ventas");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Información del Cliente")));

        txtCedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaClienteActionPerformed(evt);
            }
        });

        lblCliente.setText("Cliente:");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblNombreCliente.setText("[Nombre del Cliente]");

        btnRegistrarNuevoCliente.setText("Nuevo Cliente");
        btnRegistrarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNuevoClienteActionPerformed(evt);
            }
        });

        btnMenuPrincipal.setText("Menú Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarCliente)
                .addGap(44, 44, 44)
                .addComponent(lblNombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarNuevoCliente)
                .addGap(18, 18, 18)
                .addComponent(btnMenuPrincipal)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(lblNombreCliente)
                    .addComponent(btnRegistrarNuevoCliente)
                    .addComponent(btnMenuPrincipal))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos Disponibles"));

        tablaProductosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Categoría", "Precio", "Stock Disponible"
            }
        ));
        jScrollPane1.setViewportView(tablaProductosDisponibles);

        txtBuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarProductosActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar:");

        jLabel2.setText("Cantidad:");

        btnAgregarAlCarrito.setText("Agregar");
        btnAgregarAlCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlCarritoActionPerformed(evt);
            }
        });

        btnLimpiarBusqueda.setText("Reset");
        btnLimpiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(spinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregarAlCarrito)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimpiarBusqueda)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarBusqueda))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarAlCarrito))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrito de Compras"));

        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Precio Unidad", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(tablaCarrito);

        btnEliminarDelCarrito.setText("Eliminar");
        btnEliminarDelCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDelCarritoActionPerformed(evt);
            }
        });

        btnModificarCantidad.setText("Editar Cantidad");
        btnModificarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnEliminarDelCarrito)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarCantidad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarDelCarrito)
                    .addComponent(btnModificarCantidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen y Totales"));

        jLabel3.setText("Subtotal:");

        lblSubtotal.setText("₡0.00");

        jLabel5.setText("IVA (13%):");

        lblIVA.setText("₡0.00");

        jLabel7.setText("TOTAL:");

        lblTotal.setText("₡0.00");

        btnCancelarVenta.setText("Cancelar Venta");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });

        btnFinalizarVenta.setText("Finalizar Venta");
        btnFinalizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarVenta)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarVenta)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSubtotal)
                    .addComponent(jLabel5)
                    .addComponent(lblIVA)
                    .addComponent(jLabel7)
                    .addComponent(lblTotal))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarVenta)
                    .addComponent(btnFinalizarVenta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Configuración inicial de componentes
     */
    private void configurarComponentes() {
        // Deshabilitar controles hasta que se seleccione un cliente
        deshabilitarControlesVenta();

        // Configurar spinner de cantidad
        spinnerCantidad.setValue(1);
        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        // Limpiar label de nombre cliente
        lblNombreCliente.setText("");
    }

    /**
     * Deshabilitar controles de venta hasta que haya cliente
     */
    private void deshabilitarControlesVenta() {
        tablaProductosDisponibles.setEnabled(false);
        txtBuscarProductos.setEnabled(false);
        spinnerCantidad.setEnabled(false);
        btnAgregarAlCarrito.setEnabled(false);
        btnEliminarDelCarrito.setEnabled(false);
        btnModificarCantidad.setEnabled(false);
        btnFinalizarVenta.setEnabled(false);
    }

    /**
     * Habilitar controles de venta cuando hay cliente
     */
    private void habilitarControlesVenta() {
        tablaProductosDisponibles.setEnabled(true);
        txtBuscarProductos.setEnabled(true);
        spinnerCantidad.setEnabled(true);
        btnAgregarAlCarrito.setEnabled(true);
        btnEliminarDelCarrito.setEnabled(true);
        btnModificarCantidad.setEnabled(true);
        btnFinalizarVenta.setEnabled(true);
    }

    /**
     * Cargar productos del inventario en la tabla
     */
    private void cargarProductosEnTabla() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaProductosDisponibles.getModel();
        modelo.setRowCount(0);

        for (Producto p : inventario.obtenerTodosLosProductos()) {
            Object[] fila = {
                p.getCodigoProducto(),
                p.getNombreProducto(),
                p.getCategoriaProducto(),
                String.format("₡%.2f", p.getPrecioProducto()),
                p.getCantidadStock()
            };
            modelo.addRow(fila);
        }
    }

    /**
     * Actualizar la tabla del carrito
     */
    private void actualizarTablaCarrito() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaCarrito.getModel();
        modelo.setRowCount(0);

        for (ItemCarrito item : carrito) {
            Object[] fila = {
                item.getProducto().getCodigoProducto(),
                item.getProducto().getNombreProducto(),
                item.getCantidad(),
                String.format("₡%.2f", item.getProducto().getPrecioProducto()),
                String.format("₡%.2f", item.getSubtotal())
            };
            modelo.addRow(fila);
        }

        actualizarTotales();
    }

    /**
     * Calcular y actualizar los totales
     */
    private void actualizarTotales() {
        double subtotal = 0;

        for (ItemCarrito item : carrito) {
            subtotal += item.getSubtotal();
        }

        double iva = subtotal * 0.13;
        double total = subtotal + iva;

        lblSubtotal.setText(String.format("₡%.2f", subtotal));
        lblIVA.setText(String.format("₡%.2f", iva));
        lblTotal.setText(String.format("₡%.2f", total));
    }

    /**
     * Limpiar venta y resetear formulario
     */
    private void limpiarVenta() {
        carrito.clear();
        clienteActual = null;
        txtCedulaCliente.setText("");
        lblNombreCliente.setText("");
        actualizarTablaCarrito();
        deshabilitarControlesVenta();
        spinnerCantidad.setValue(1);
        txtBuscarProductos.setText("");
    }

    /**
     * Obtener cantidad de un producto que ya está en el carrito
     */
    private int obtenerCantidadEnCarrito(String codigoProducto) {
        for (ItemCarrito item : carrito) {
            if (item.getProducto().getCodigoProducto().equals(codigoProducto)) {
                return item.getCantidad();
            }
        }
        return 0;
    }

    private void txtCedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaClienteActionPerformed
        // Permitir buscar con Enter
        btnBuscarClienteActionPerformed(evt);
    }//GEN-LAST:event_txtCedulaClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        String cedula = txtCedulaCliente.getText().trim();

        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una cédula.");
            return;
        }

        clienteActual = gestorClientes.buscarCliente(cedula);

        if (clienteActual != null) {
            lblNombreCliente.setText(clienteActual.getNombre() + " " + clienteActual.getApellido());
            habilitarControlesVenta();
            JOptionPane.showMessageDialog(this, "Cliente encontrado!");
        } else {
            lblNombreCliente.setText("");
            deshabilitarControlesVenta();

            int respuesta = JOptionPane.showConfirmDialog(
                    this,
                    "Cliente no encontrado. ¿Desea registrarlo?",
                    "Cliente no encontrado",
                    JOptionPane.YES_NO_OPTION
            );

            if (respuesta == JOptionPane.YES_OPTION) {
                btnRegistrarNuevoClienteActionPerformed(null);
            }
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnRegistrarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNuevoClienteActionPerformed
        this.setEnabled(false);

        AgregarNuevoClienteFrame frame = new AgregarNuevoClienteFrame(gestorClientes, null);

        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                VentasFrame.this.setEnabled(true);
                VentasFrame.this.toFront();
                VentasFrame.this.requestFocus();

                // Intentar buscar el cliente recién creado
                String cedula = txtCedulaCliente.getText().trim();
                if (!cedula.isEmpty()) {
                    clienteActual = gestorClientes.buscarCliente(cedula);
                    if (clienteActual != null) {
                        lblNombreCliente.setText(clienteActual.getNombre() + " " + clienteActual.getApellido());
                        habilitarControlesVenta();
                    }
                }
            }
        });

        frame.setVisible(true);
    }//GEN-LAST:event_btnRegistrarNuevoClienteActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        if (!carrito.isEmpty()) {
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "Hay una venta en proceso. ¿Está seguro que desea salir?",
                    "Confirmar Salida",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmacion != JOptionPane.YES_OPTION) {
                return;
            }
        }

        this.dispose();
        menuPadre.setVisible(true);
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void txtBuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarProductosActionPerformed
        String busqueda = txtBuscarProductos.getText().trim().toLowerCase();

        if (busqueda.isEmpty()) {
            cargarProductosEnTabla();
            return;
        }

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaProductosDisponibles.getModel();
        modelo.setRowCount(0);

        for (Producto p : inventario.obtenerTodosLosProductos()) {
            if (p.getNombreProducto().toLowerCase().contains(busqueda)
                    || p.getCodigoProducto().toLowerCase().contains(busqueda)
                    || p.getCategoriaProducto().toLowerCase().contains(busqueda)) {

                Object[] fila = {
                    p.getCodigoProducto(),
                    p.getNombreProducto(),
                    p.getCategoriaProducto(),
                    String.format("₡%.2f", p.getPrecioProducto()),
                    p.getCantidadStock()
                };
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_txtBuscarProductosActionPerformed

    private void btnAgregarAlCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlCarritoActionPerformed
        int filaSeleccionada = tablaProductosDisponibles.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto.");
            return;
        }

        String codigoProducto = tablaProductosDisponibles.getValueAt(filaSeleccionada, 0).toString();
        Producto producto = inventario.buscarProducto(codigoProducto);

        if (producto == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            return;
        }

        int cantidadSolicitada = (int) spinnerCantidad.getValue();

        // Validar stock disponible
        int cantidadEnCarrito = obtenerCantidadEnCarrito(codigoProducto);
        int stockDisponible = producto.getCantidadStock() - cantidadEnCarrito;

        if (cantidadSolicitada > stockDisponible) {
            JOptionPane.showMessageDialog(
                    this,
                    "Stock insuficiente. Disponible: " + stockDisponible,
                    "Stock Insuficiente",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Verificar si el producto ya está en el carrito
        boolean encontrado = false;
        for (ItemCarrito item : carrito) {
            if (item.getProducto().getCodigoProducto().equals(codigoProducto)) {
                item.setCantidad(item.getCantidad() + cantidadSolicitada);
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            carrito.add(new ItemCarrito(producto, cantidadSolicitada));
        }

        actualizarTablaCarrito();
        spinnerCantidad.setValue(1);
        JOptionPane.showMessageDialog(this, "Producto agregado al carrito.");
    }//GEN-LAST:event_btnAgregarAlCarritoActionPerformed

    private void btnEliminarDelCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDelCarritoActionPerformed
        int filaSeleccionada = tablaCarrito.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto del carrito.");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea eliminar este producto del carrito?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            carrito.remove(filaSeleccionada);
            actualizarTablaCarrito();
        }
    }//GEN-LAST:event_btnEliminarDelCarritoActionPerformed

    private void btnModificarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCantidadActionPerformed
        int filaSeleccionada = tablaCarrito.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto del carrito.");
            return;
        }

        ItemCarrito item = carrito.get(filaSeleccionada);

        String input = JOptionPane.showInputDialog(
                this,
                "Nueva cantidad (Stock disponible: " + item.getProducto().getCantidadStock() + "):",
                item.getCantidad()
        );

        if (input != null && !input.trim().isEmpty()) {
            try {
                int nuevaCantidad = Integer.parseInt(input.trim());

                if (nuevaCantidad <= 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.");
                    return;
                }

                if (nuevaCantidad > item.getProducto().getCantidadStock()) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Stock insuficiente. Disponible: " + item.getProducto().getCantidadStock(),
                            "Stock Insuficiente",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }

                item.setCantidad(nuevaCantidad);
                actualizarTablaCarrito();

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Cantidad inválida.");
            }
        }
    }//GEN-LAST:event_btnModificarCantidadActionPerformed

    private void btnFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVentaActionPerformed
        if (carrito.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío.");
            return;
        }

        if (clienteActual == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
            return;
        }

        // Crear la venta
        String numeroVenta = gestorVentas.generarNumeroVenta();
        Venta venta = new Venta(numeroVenta, clienteActual, nombreUsuarioActual);

        // Agregar detalles
        for (ItemCarrito item : carrito) {
            venta.agregarDetalle(item.toDetalleVenta());
        }

        // Mostrar resumen
        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                venta.obtenerResumen(),
                "Confirmar Venta",
                JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Finalizar venta y generar factura
            Factura factura = venta.finalizarVenta();
            if (factura != null) {
                // Registrar venta y factura
                gestorVentas.registrarVenta(venta);
                gestorVentas.registrarFactura(factura);
                historial.agregarFactura(factura);

                // Mostrar factura
                JOptionPane.showMessageDialog(
                        this,
                        factura.generarFacturaTexto(),
                        "Factura Generada",
                        JOptionPane.INFORMATION_MESSAGE
                );

                // Limpiar todo para nueva venta
                limpiarVenta();
                cargarProductosEnTabla();
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Error: Stock insuficiente para completar la venta.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnFinalizarVentaActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        if (!carrito.isEmpty()) {
            int confirmacion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro que desea cancelar la venta?",
                    "Confirmar Cancelación",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                limpiarVenta();
            }
        } else {
            limpiarVenta();
        }
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void btnLimpiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBusquedaActionPerformed
        txtBuscarProductos.setText("");
        cargarProductosEnTabla();
    }//GEN-LAST:event_btnLimpiarBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlCarrito;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnEliminarDelCarrito;
    private javax.swing.JButton btnFinalizarVenta;
    private javax.swing.JButton btnLimpiarBusqueda;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnModificarCantidad;
    private javax.swing.JButton btnRegistrarNuevoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tablaProductosDisponibles;
    private javax.swing.JTextField txtBuscarProductos;
    private javax.swing.JTextField txtCedulaCliente;
    // End of variables declaration//GEN-END:variables
}
